### ISSUE TITLE
Missing CSRF Token Cookie

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-test-helper#13]
Version: 0.2.3
CakePHP: 3.8.9

I just tested the plugin in an application which has the CSRF protectoin activated by default.
Submitting anything under ``/test-helper`` leads to a ``Missing CSRF token cookie`` exception.

Either this can be worked around or a warning should be added to the documentation

**Comment by dereuromark** [comment]
How can we disable this check as it is not needed for such a test backend on local dev.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-test-helper/commit/aa3997ef0aec9993c7b50107e6ea80029dd448ac
