### ISSUE TITLE
Importing Model in Fixture leads to Invalid Comparison Result

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-test-helper#14]
Version: 0.2.3
CakePHP: 3.8.9

I compared the fixture(s) of a plugin in an application that imports the model.

The fixture:

```` php
<?php
namespace PartnerQuiz\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * Partner Quiz Submissions Fixtures
 */
class PartnerQuizSubmissionsFixture extends TestFixture
{
    /**
     * Import from model
     *
     * @var array
     */
    public $import = ['model' => 'PartnerQuizSubmissions'];

    /**
     * Init method
     *
     * @return void
     */
    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'salutation' => 'L',
                'last_name' => 'Müller',
                'first_name' => 'Markus',
                'company_name' => 'Müller GmbH',
                'date_of_birth' => '1953-10-01 00:00:00',
                'email' => 'markus.mueller@mueller-gmbh.ch',
                'quiz_answer' => 12345,
                'participation_conditions_accepted' => 1,
                'newsletter_subscribed' => 1,
                'created' => '2019-11-28 15:05:24',
                'modified' => '2019-11-28 15:05:24',
            ],
        ];
        parent::init();
    }
}

````

The comparison result:

````
>php bin/cake.php fixture_check -v -p PartnerQuiz
1 fixtures found, processing:

Comparing `PartnerQuiz\Test\Fixture\PartnerQuizSubmissionsFixture` with table `partner_quiz_submissions`
Live DB has fields that are not in PartnerQuiz\Test\Fixture\PartnerQuizSubmissionsFixture
 * company_name
 * created
 * date_of_birth
 * email
 * first_name
 * id
 * last_name
 * modified
 * newsletter_subscribed
 * participation_conditions_accepted
 * quiz_answer
 * salutation

The following constraints mismatch:
 * Constraint "primary" {"type":"primary","columns":["id"],"length":[]} is missing in fixture, but in live DB.
 * Constraint "UX_email" {"type":"unique","columns":["email"],"length":[]} is missing in fixture, but in live DB.


Copy-paste the following for fixture updating:
bin/cake bake fixture partner_quiz_submissions -f -p PartnerQuiz
Differences detected, check your fixtures and DB.
````

The mismatch found doesn't make sense, as it imports from the model:

````
The following constraints mismatch:
 * Constraint "primary" {"type":"primary","columns":["id"],"length":[]} is missing in fixture, but in live DB.
 * Constraint "UX_email" {"type":"unique","columns":["email"],"length":[]} is missing in fixture, but in live DB.
````

In such a case I would expect no diff.

**Comment by dereuromark** [comment]
what do you mean with "import from the model"?
If those constraints are not set in your DB on prod, why would those not error on local dev, if that DB there doesnt contain it through fixture setup? As the tests would otherwise behave differently and can false positive where they would fail on prod.

**Comment by dereuromark** [comment]
public $import = ['model' => 'PartnerQuizSubmissions'];

Does that also import the constraints? Or does it maybe miss those?
It could also be a fixture issue?

**Comment by ravage84** [comment]
> what do you mean with "import from the model"?

```` php 
public $import = ['model' => 'PartnerQuizSubmissions'];
````

> Does that also import the constraints? Or does it maybe miss those?

To be honest, I don't know. The documentation doesn't say anything about it:

https://book.cakephp.org/3/en/development/testing.html#importing-table-information

But I assume this info get lost somehow.

> It could also be a fixture issue? As it uses the table after it got created afaik.

Might be.

Alternatively, you could simply disable the check of this additoinal info, as all should be fine, anyway.

**Comment by dereuromark** [comment]
I would first assert that the constraints in your test db are in place as expected by prod DB.
Otherwise this is dangerous to run tests with.

If that is the case, then we need to fix the check or allow some silencing based on the "import" option being used.

**Comment by ravage84** [comment]
> I would first assert that the constraints in your test db are in place as expected by prod DB.

They seem to be:

![grafik](https://user-images.githubusercontent.com/625761/76217631-14239b80-6213-11ea-82c4-2a9eba849c06.png)

> Make a test that should fail (on prod for sure) regarding those constraints. Some unique issue (and bypass model validation here!) for email for example.

When I disable the validation, it will lead to a "Value already used" error by the database, as expected, due to the unique index.

> If that is the case, then we need to fix the check or allow some silencing based on the "import" option being used.

I would not check the schema, if either import from model or table is used, as the schema shold be fine in those cases.

https://github.com/cakephp/cakephp/blob/3.8.9/src/TestSuite/Fixture/TestFixture.php#L225

Odd, after this it seems to go the same way as when only ``table`` is filled.

**Comment by dereuromark** [comment]
So is there something left we shall do as PR to fix things?
