### ISSUE TITLE
fixture_check Command doesn't check plugins by default

### ISSUE THREAD

**Issue by ravage84** [dereuromark/cakephp-test-helper#15]
Version: 0.2.3
CakePHP: 3.8.9

When executing the ``fixture_check`` command on an applicaton with no fixtures in the app directly but some in one of the several plugins, it leads to no fixtures found

````
>php bin/cake.php fixture_check -v
0 fixtures found, processing:


All fine :)
````

As a total noob of this plugin I would have exptected that this command goes through all of my plugins by default. At least, I would have expected that the plugin tells me which pats of the app it checks. This way, it's clear.

**Comment by dereuromark** [comment]
You can make a PR here, the plugin part is documented in -h however.

**Comment by dereuromark** [comment]
Does https://github.com/dereuromark/cakephp-test-helper/commit/641e0e526fc081caa1235635815ec3c7d7492dc9 help?

**Comment by ravage84** [comment]
> 
> 
> Does [641e0e5](https://github.com/dereuromark/cakephp-test-helper/commit/641e0e526fc081caa1235635815ec3c7d7492dc9) help?

Yes, this is a good start.
Still, I think the command should scan everything (app, plus plugins under ``plugins`` **and** ``vendor``) by default. ([Expectation management](https://en.wikipedia.org/wiki/Principle_of_least_astonishment))

**Comment by dereuromark** [comment]
I am fine with a PR here that also includes an app-only option and is intuitive here.
Currently "expectations" are IMO respected as this is also how all other commands work by default: migrations, bake, ide helper and tons of other commands.
