### ISSUE TITLE
Vendor plugins don't work

### ISSUE THREAD

**Issue by highstrike** [dereuromark/cakephp-test-helper#5]
trying to generate tests for my plugin (which is in `vendor/` doesn't work)

i clicked the "+" icon which redirected into 404 `http://dev.local/test-helper/test-cases/component/Unimatrix%2FFrontend`

## image preview 

![image](https://user-images.githubusercontent.com/2379538/42954460-7471f9fc-8b85-11e8-80b0-f6d92e52bd1d.png)

**Comment by dereuromark** [comment]
Looks like the / of the vendor prefix doesnt work.
Are you able to create a patch here?

**Comment by dereuromark** [comment]
Looks fixed
